/* eslint-disable react-hooks/rules-of-hooks */
/* eslint-disable @typescript-eslint/no-explicit-any */
import React, { useState, useEffect, useRef } from 'react';
import { ArrowLeft, Eye, Calendar, User, Loader2, Search, Download, Trash2, MoveLeft } from 'lucide-react';
import { Navigate, useParams } from 'react-router-dom';
import { API_URLS } from '../services/api-constants';
import { toPng } from 'html-to-image';


const FORM_INFO = {
  form_id: 1,
  form_name: "Navani FormsData",
  description: "Make the public form conversation"
};

const FormSubmissionHistory = () => {
  const [currentView, setCurrentView] = useState('list'); // 'list' or 'details'
  const [selectedSubmission, setSelectedSubmission] = useState<any>(null);
  const [submissions, setSubmissions] = useState<any>([]);
  const [filteredSubmissions, setFilteredSubmissions] = useState<any>([]);
  const [htmlTemplate, setHtmlTemplate] = useState('');
  const [loading, setLoading] = useState(false);
  const [searchTerm, setSearchTerm] = useState('');
  const [formInfo, setFormInfo] = useState(FORM_INFO);
  const { id: formId } = useParams();

    const containerRef = useRef();



  // Fetch submissions on component mount
  useEffect(() => {
    fetchSubmissions();
  }, []);

 const downloadCsv = async (formId: number) => {
  try {
    const response = await fetch(`${import.meta.env.VITE_API_URL}/forms/${formId}/submissions/export`, {
      method: 'GET',
      headers: {
        'Content-Type': 'text/csv',
      },
    });

    if (!response.ok) {
      throw new Error('Failed to download CSV');
    }

    // Convert response to Blob
    const blob = await response.blob();

    // Create a temporary download link
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `form_${formId}_submissions.csv`;
    document.body.appendChild(a);
    a.click();
    a.remove();
    window.URL.revokeObjectURL(url);
  } catch (error) {
    console.error('Error downloading CSV:', error);
  }
}


  const downloadImage = async () => {
    if (!containerRef.current) return;

    try {
      const dataUrl = await toPng(containerRef.current, {
        backgroundColor: '#ffffff',
        quality: 1,
        pixelRatio: 2,
      });
      const link = document.createElement('a');
      link.href = dataUrl;
      link.download = 'form_submission.png';
      link.click();
    } catch (err) {
      console.error('Error generating image:', err);
    }
  };





  // Fetch submissions for a form
  const fetchSubmissions = async () => {
    setLoading(true);
    try {
        console.log("Form ID:", formId);
      // Replace with your actual API call
    //   Get formId from URL params:
      const response = await fetch(`${import.meta.env.VITE_API_URL}/forms/${formId}/submissions`);
      const data = await response.json();
      setSubmissions(data.submissions);
      setFormInfo(data.form);
      setFilteredSubmissions(data.submissions);

      setLoading(false);
      
      // Using sample data
    //   setTimeout(() => {
    //     setSubmissions(SAMPLE_SUBMISSIONS);
    //     setFilteredSubmissions(SAMPLE_SUBMISSIONS);
    //     setLoading(false);
    //   }, 500);
    } catch (error) {
      console.error('Error fetching submissions:', error);
      setLoading(false);
    }
  };

  // Fetch HTML template generated by NestJS backend
  const fetchHtmlTemplate = async (submissionId: any): Promise<any> => {
    setLoading(true);
    try {

        const getEmailHTML = submissions.find((sub: any) => sub.submission_id === submissionId);
        if(getEmailHTML?.html_email) {
            const htmlContent = getEmailHTML.html_email;
            setHtmlTemplate(htmlContent);
            setLoading(false);
        }
        else {
            setHtmlTemplate('<p>No HTML template found for this submission.</p>');
            setLoading(false);
        }
      // This will call your NestJS endpoint that returns the generated HTML
    //   const response = await fetch(`/api/submissions/${submissionId}/html`);
    //   const data = await response.json();
      
      // The backend should return { html: "...your generated HTML..." }
    //   setHtmlTemplate(data.html);
    //   setLoading(false);
    } catch (error) {
      console.error('Error fetching HTML template:', error);
      setLoading(false);
    }
  };

  const handleSubmissionClick = (submission: any) => {
    console.log("Clicked submission:", submission);
    setSelectedSubmission(submission);
    fetchHtmlTemplate(submission?.submission_id);
    setCurrentView('details');
  };

  const handleBackToList = () => {
    setCurrentView('list');
    setSelectedSubmission(null);
    setHtmlTemplate('');
  };

  const handleBackToDashboard = () => {
    window.location.href = '/dashboard';    
  }

  const formatDate = (dateString: string | number | Date) => {
    return new Date(dateString).toLocaleString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  };

  // Search functionality
  const handleSearch = (term: any) => {
    setSearchTerm(term);
    if (!term.trim()) {
      setFilteredSubmissions(submissions);
      return;
    }

    const filtered = submissions.filter((submission: any) => {
      const data = submission.submission_json.data;
      const searchLower = term?.trim().toLowerCase();
      
      return Object.values(data).some(value => 
        value && value.toString().toLowerCase().includes(searchLower)
      );
    });
    
    setFilteredSubmissions(filtered);
  };

  // Get first few fields for preview in submission list
  const getPreviewFields = (data: ArrayLike<unknown> | { [s: string]: unknown; }) => {
    const entries = Object.entries(data).slice(0, 3);
    return entries;
  };

  // Submissions List View
  if (currentView === 'list') {
    return (
      <div className="min-h-screen bg-gradient-to-br from-gray-50 to-gray-100 p-4 md:p-6">
        <div className="max-w-7xl mx-auto">
          <div className="bg-white rounded-xl shadow-sm p-6 md:p-8 mb-6 border border-gray-200">
            <div className="flex items-start gap-4 mb-4">
              <div className="p-3 bg-orange-100 rounded-xl">
                <svg className="w-8 h-8 text-orange-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                </svg>
              </div>
              <div className="flex-1">
                <h1 className="text-2xl md:text-3xl font-bold text-gray-800 mb-2">{formInfo.form_name}</h1>
                {formInfo.description && (
                  <p className="text-gray-600">{formInfo.description}</p>
                )}
              </div>

               <div>
                <button
              onClick={handleBackToDashboard}
              className="flex items-center gap-2 text-gray-600 hover:text-gray-800 transition font-medium"
            >
              <ArrowLeft size={20} />
              Back to Dashboard
            </button>
            </div>

            </div>
            <div className="flex flex-wrap items-center gap-4 pt-4 border-t border-gray-100">
              <span className="bg-orange-100 text-orange-700 px-4 py-2 rounded-full text-sm font-semibold">
                {filteredSubmissions.length} {filteredSubmissions.length === 1 ? 'Submission' : 'Submissions'}
              </span>
              {filteredSubmissions.length > 0 && (
                <button onClick={() => downloadCsv(formInfo.form_id)} className="flex items-center gap-2 text-gray-600 hover:text-gray-800 text-sm font-medium transition">
                  <Download size={16} />
                  Export All
                </button>
              )}
            </div>
          </div>

          {/* Search Bar */}
          <div className="mb-6">
            <div className="relative max-w-md">
              <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400" size={20} />
              <input
                type="text"
                placeholder="Search submissions..."
                value={searchTerm}
                onChange={(e) => handleSearch(e.target.value)}
                className="w-full pl-10 pr-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-orange-500 focus:border-transparent"
              />
            </div>
          </div>

          {loading ? (
            <div className="flex items-center justify-center py-20">
              <Loader2 className="animate-spin text-orange-500" size={40} />
            </div>
          ) : filteredSubmissions.length === 0 ? (
            <div className="bg-white rounded-xl shadow-sm p-12 text-center border border-gray-200">
              <svg className="w-16 h-16 mx-auto text-gray-300 mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
              </svg>
              <h3 className="text-xl font-semibold text-gray-800 mb-2">
                {searchTerm ? 'No submissions found' : 'No submissions yet'}
              </h3>
              <p className="text-gray-600">
                {searchTerm ? 'Try adjusting your search terms' : 'Submissions will appear here once users fill out your form'}
              </p>
            </div>
          ) : (
            <div className="space-y-4">
              {filteredSubmissions.map((submission: any) => {
                const data = submission.submission_json.data;
                const previewFields = getPreviewFields(data);
                console.log("previewFields::::", previewFields)
                
                return (
                  <div
                    key={submission.submission_id}
                    className="bg-white rounded-xl shadow-sm p-6 border border-gray-200 hover:shadow-lg transition-all duration-300 cursor-pointer hover:border-orange-200"
                    onClick={() => handleSubmissionClick(submission)}
                  >
                    <div className="flex flex-col lg:flex-row lg:items-start lg:justify-between gap-4">
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2 mb-3">
                          <div className="p-2 bg-gray-100 rounded-lg">
                            <User className="text-gray-600" size={18} />
                          </div>
                          <div className="flex items-center gap-2 text-xs text-gray-500">
                            <Calendar size={14} />
                            {formatDate(submission.created_at)}
                          </div>
                        </div>
                        
                        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
                          {previewFields.map(([key, value]) => (
                            <div key={key} className="min-w-0">
                              <div className="text-xs font-medium text-gray-500 uppercase tracking-wide mb-1">
                                {key.replace(/([A-Z])/g, ' $1').replace(/_/g, ' ').trim()}
                              </div>
                              <div className="text-sm text-gray-800 truncate font-medium">
                                {value?.toString()}
                              </div>
                            </div>
                          ))}
                        </div>
                        
                        {Object.keys(data).length > 3 && (
                          <div className="mt-3 text-xs text-gray-500">
                            +{Object.keys(data).length - 3} more fields
                          </div>
                        )}
                      </div>
                      
                      <button className="flex items-center gap-2 bg-orange-500 hover:bg-orange-600 text-white px-5 py-2.5 rounded-lg transition font-medium shadow-sm hover:shadow whitespace-nowrap">
                        <Eye size={18} />
                        View Details
                      </button>
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </div>
      </div>
    );
  }

  // Submission Details View - Rendering HTML Template from Backend
  if (currentView === 'details') {
    return (
      <div className="min-h-screen bg-gradient-to-br from-gray-50 to-gray-100 p-4 md:p-6">
        <div className="max-w-5xl mx-auto">
          <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 mb-6">
            <button
              onClick={handleBackToList}
              className="flex items-center gap-2 text-gray-600 hover:text-gray-800 transition font-medium"
            >
              <ArrowLeft size={20} />
              Back to Submissions
            </button>
            
            <div className="flex gap-2">
              <button onClick={downloadImage} className="flex items-center gap-2 px-4 py-2 border border-gray-300 rounded-lg hover:bg-gray-50 transition text-sm font-medium">
                <Download size={16} />
                Download as Image
              </button>
              {/* <button className="flex items-center gap-2 px-4 py-2 border border-red-300 text-red-600 rounded-lg hover:bg-red-50 transition text-sm font-medium">
                <Trash2 size={16} />
                Delete
              </button> */}
            </div>
          </div>

          {loading ? (
            <div className="bg-white rounded-xl shadow-lg p-20 text-center">
              <Loader2 className="animate-spin text-orange-500 mx-auto mb-4" size={48} />
              <p className="text-gray-600">Loading submission details...</p>
            </div>
          ) : (
            <div className="bg-white rounded-xl shadow-lg border border-gray-200 overflow-hidden">
              {/* Render the HTML template received from your NestJS backend */}
              <iframe
                srcDoc={htmlTemplate}
                className="w-full border-0"
                style={{ minHeight: '700px', height: '100%' }}
                title="Submission Details"
                sandbox="allow-same-origin"
              />
            </div>
          )}
        </div>
      </div>
    );
  }
};

export default FormSubmissionHistory;